### ISSUE TITLE
Add support for databases

### ISSUE THREAD

**Issue by JCyberSec** [zerofox-oss/phishpond#14]
It would be nice to be able to simulate a MySQL (other dbs are available) so if a phishing kit writes victim data to a database this can be viewed in a secure way.

Having the ability to easily change the name of the database, username, and password is essential.

**Comment by zmallen** [comment]
This is a great idea! Will try to add in for some work. I think having a way to configure certain parameters in the docker-compose would be good..

I would imagine we should identify what PHP calls need to be shimmed for writing to a database
